
version: "3.8"

services:
  php:
    build:
      context: ./docker/php/
      args:
        - UID=${LOCAL_UID:-1000}
        - GID=${LOCAL_GID:-1000}
    command: 'bash -c "tail -f /dev/null"'
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql

  mysql:
    image: mysql:8.0
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci' #,
    ]
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_ROOT_PASSWORD: 'password'
